app:
  name: api-bff
  image:
    repository: "onecx/onecx-workspace-api-bff"
  operator:
    # Permission
    permission:
      enabled: true
      spec:
        permissions:
          menu:
            ext-api-req: permission to request menu api
    keycloak:
      client:
        enabled: true
        spec:
          kcConfig:
            defaultClientScopes: [ ocx-ws:read, ocx-pm:read ]
